name: Weather Data

on:
  #push:
  #  branches:
  #    - main
  #pull_request:
  #  branches:
  #    - main
  schedule:
    - cron: '0 10 * * *'  # Runs at 10am every day (UTC time)
  workflow_dispatch:  # Allow manual triggering of the workflow

permissions:
  contents: write  # Grants the workflow permission to push changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4

      - name: Execute weather.sh script
        run: ./data/weather.sh

      - name: Commit and push changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .  # Add all changes to staging
          git commit -m "Update weather data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # use GitHub token for authentication (it automatic, dont need to change)

