name: Weather Data

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 10 * * *'  # Runs at 10am every day (UTC time)
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4

      - name: Execute weather.sh script
        run: ./data/weather.sh

      - name: Commit and push changes
        run: |
          git config --local user.name "holmstead"
          git config --local user.email "holmstead@protonmail.com"
          git add .  # Add all changes to staging
          git commit -m "Update weather data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # use GitHub token for authentication (it automatic, dont need to change)

